### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by yuanjun-liu** [Skyyyy0920/MTNet#7]
I run the code on the self-built datasets, it runs well on NYC and TKY datasets, but has problem on the gowalla-ca dataset.

Do you have any idea about the following RecursionError?

```
Traceback (most recent call last):
  File "./main.py", line 163, in <module>
    mobility_tree = construct_MobilityTree(trajectory, label, args.n_time_slot + 1, args.plot_tree)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./utils.py", line 176, in construct_MobilityTree
    add_day_node(tree, trajectory, labels, len(trajectory) - 1, nary)
  File "./utils.py", line 168, in add_day_node
    period_node_id = add_period_node(tree, day_trajectory[i], nary)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./utils.py", line 150, in add_period_node
    add_true_node(tree, trajectory, len(trajectory), node_id, nary)
  File "./utils.py", line 139, in add_true_node
    add_true_node(tree, trajectory, index - (nary - 1), sub_parent_node_id, nary)
  File "./utils.py", line 139, in add_true_node
    add_true_node(tree, trajectory, index - (nary - 1), sub_parent_node_id, nary)
  File "./utils.py", line 139, in add_true_node
    add_true_node(tree, trajectory, index - (nary - 1), sub_parent_node_id, nary)
  [Previous line repeated 991 more times]
  File "./utils.py", line 127, in add_true_node
    tree.add_node(node_id, x=node['features'], time=node['time'], y=node['labels'], mask=1, mask2=0, type=2)
  File "/public/home/anliu/anaconda3/lib/python3.11/site-packages/networkx/classes/digraph.py", line 466, in add_node
    attr_dict.update(attr)
RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by Skyyyy0920** [comment]
I haven't encountered this issue in my experiments either, but after some searching, it seems like the problem may be due to excessive recursion depth, possibly caused by an issue during tree construction. I suggest first increasing the default recursion depth to test if the problem persists. Additionally, you can try running in debug mode to examine why excessive recursion occurs during tree construction, leading to too many recursive calls. Given that you modified the dataset, I suspect this might be the cause.
